### ISSUE TITLE
add a option can directly use local juicer tool and py script

### ISSUE THREAD

**Issue by shangguandong1996** [nf-core/hicar#71]
### Description of feature

Hi.
I am using the hicar pipeline, I have downloaded the whole hicar image.
But it seems that my linux server have bad internet connection with github, so that every time I try to run hicar. it will report the 

```bash
No such file: https://github.com/aidenlab/Juicebox/releases/download/v2.13.06/juicer_tools_2.13.06.jar 

# or 
No such file: https://raw.githubusercontent.com/ijuric/MAPS/91c9c360092b25a217d91b9ea07eba5dd2ac72f4/bin/utils/genomic_features_generator/scripts/merge_map.py
```

I am wondering whether you can add a option that I can use the local file

Best wishes
Guandong Shang

**Comment by shangguandong1996** [comment]
I have tried to download the juicer tool jar, but I do not find a option that I can use the local py script

```
sgd@localhost ~/newProject/202207/HiCAR_SIM3d_202207/rawdata
$ nextflow run /data5/sgd_data/biosoft/nf-core/nf-core-hicar-1.0.0/workflow --input samplesheet.csv --outdir ../result --fasta ~/reference/genome/TAIR10/Athaliana.fa --bwa_index ~/reference/index/bowtie2/TAIR10 --gtf ~/reference/annoation/Athaliana/Araport11/Araport11_GFF3_genes_transposons.201606.gtf --macs_gsize 1.1e8 -profile singularity --juicer_tools_jar /data5/sgd_data/biosoft/juicer_tools_2.13.06.jar 

```

```
Jul-01 15:37:05.063 [main] DEBUG nextflow.Session - Session aborted -- Cause: https://raw.githubusercontent.com/ijuric/MAPS/91c9c360092b25a217d91b9ea07eba5dd2ac72f4/bin/utils/genomic_features_generator/scripts/merge_map.py
Jul-01 15:37:05.091 [main] ERROR nextflow.cli.Launcher - https://raw.githubusercontent.com/ijuric/MAPS/91c9c360092b25a217d91b9ea07eba5dd2ac72f4/bin/utils/genomic_features_generator/scripts/merge_map.py
java.nio.file.NoSuchFileException: https://raw.githubusercontent.com/ijuric/MAPS/91c9c360092b25a217d91b9ea07eba5dd2ac72f4/bin/utils/genomic_features_generator/scripts/merge_map.py
	at nextflow.file.FileHelper.checkIfExists(FileHelper.groovy:1032)
	at nextflow.file.FileHelper$checkIfExists$2.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at nextflow.Nextflow.file(Nextflow.groovy:151)
	at nextflow.Nextflow$file.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
	at Script_6f8f2413.runScript(Script_6f8f2413:59)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:169)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:207)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:201)
	at nextflow.script.IncludeDef.memoizedMethodPriv$loadModule0PathMapSession(IncludeDef.groovy:142)
	at nextflow.script.IncludeDef.access$0(IncludeDef.groovy)
	at nextflow.script.IncludeDef$__clinit__closure1.doCall(IncludeDef.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at nextflow.script.IncludeDef.loadModule0(IncludeDef.groovy)
	at nextflow.script.IncludeDef.load0(IncludeDef.groovy:114)
	at nextflow.script.IncludeDef$load0$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at Script_f1a98abd.runScript(Script_f1a98abd:47)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:169)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:308)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)
```

**Comment by shangguandong1996** [comment]
Sorry, I just find the option :). this is my mistake.
