### ISSUE TITLE
.hic file produced by hicar could not be opened by juicebox

### ISSUE THREAD

**Issue by Rhine86** [nf-core/hicar#80]
I found that the .hic file generated by hicar could not be opened by juicebox, so do the .hic file downloaded from https://nf-co.re/hicar/results#hicar/results-429087d2b13e59c3edd2e71b8005c1adc5bbb7bb/cooler/hic/, do you have any ideas? Thanks!
The error log is:
"INFO [2023-03-01 11:25:40,463] [DirectoryManager.java:72]  Fetching user directory... 
INFO [2023-03-01 11:25:40,482] [DirectoryManager.java:169]  IGV Directory: C:\Users\zhang\igv
INFO [2023-03-01 11:25:40,889] [CommandListener.java:86]  Listening on port 30000
ERROR [2023-03-01 11:26:02,486] [DatasetReaderV2.java:272]  Error reading dataset
java.io.EOFException
	at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
	at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:194)
	at juicebox.gui.SuperAdapter.unsafeLoad(SuperAdapter.java:388)
	at juicebox.gui.SuperAdapter.unsafeLoadWithTitleFix(SuperAdapter.java:483)
	at juicebox.gui.SuperAdapter$1.run(SuperAdapter.java:470)
	at juicebox.MainWindow$3.call(MainWindow.java:194)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR [2023-03-01 11:26:02,489] [SuperAdapter.java:490]  Error loading hic file
java.io.EOFException
	at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
	at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:194)
	at juicebox.gui.SuperAdapter.unsafeLoad(SuperAdapter.java:388)
	at juicebox.gui.SuperAdapter.unsafeLoadWithTitleFix(SuperAdapter.java:483)
	at juicebox.gui.SuperAdapter$1.run(SuperAdapter.java:470)
	at juicebox.MainWindow$3.call(MainWindow.java:194)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)"

**Comment by jianhong** [comment]
Did you check the version of juicebox you used in the pipeline?

**Comment by jianhong** [comment]
This error may caused by version conflict of juicebox. Please check the version of juicebox in pipeline you used and the juicebox version for visualization.
You can always reopen this issue when you still have problem with that.
